pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pawellm96/QAC07-jefit_autotest.git'
            }
        }

        stage('Clean') {
            steps {
                script { deleteDir() }
            }
        }

        stage('Restore') {
            steps {
                // Полный путь к .sln с прямыми слэшами
                bat 'dotnet restore "D:/Kurs/Jefit/QAC07-jefit_autotest/Jefit_test/Jefit_test.sln"'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build "D:/Kurs/Jefit/QAC07-jefit_autotest/Jefit_test/Jefit_test.sln" --configuration Release'
            }
        }

        stage('Test') {
            steps {
                echo "Selected ENV: ${params.ENVIRONMENT ?: 'dev'}"
                
                // Если в проекте нет категорий, запускаем все тесты
                bat 'dotnet test "D:/Kurs/Jefit/QAC07-jefit_autotest/Jefit_test/Jefit_test.sln" --logger:"trx;LogFileName=test-result.trx"'
            }
        }
    }

    post {
        always {
            // Создаём папку allure-results, если не существует
            bat 'if not exist allure-results mkdir allure-results'

            // Генерация Allure отчёта
            bat '"D:/Kurs/Allure/allure-2.35.1/bin/allure.bat" generate allure-results --clean -o allure-report'

            script {
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'allure-results']],
                    reportBuildPolicy: 'ALWAYS'
                ])
            }

            archiveArtifacts artifacts: '**/*.trx', allowEmptyArchive: true
        }

        failure {
            echo 'Test run FAILED!'
        }

        success {
            ech
