pipeline {
    agent any

    environment {
        DOTNET_CLI_HOME = '.'
        ALLURE_HOME = 'D:/Kurs/Allure/allure-2.35.1/bin'
        ALLURE_RESULTS_DIR = 'allure-results'
        ALLURE_REPORT_DIR = 'allure-report'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pawellm96/QAC07-jefit_autotest.git'
            }
        }

        stage('Restore dependencies') {
            steps {
                dir('Jefit_test') {
                    bat 'dotnet restore Jefit_test.sln'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Jefit_test') {
                    bat 'dotnet build Jefit_test.sln --configuration Release'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Jefit_test') {
                    bat 'dotnet test Jefit_test.sln --configuration Release --logger "trx;LogFileName=test_results.trx"'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                // Генерация отчета Allure напрямую через bat
                bat "\"${ALLURE_HOME}/allure.bat\" generate ${ALLURE_RESULTS_DIR} --clean -o ${ALLURE_REPORT_DIR}"
            }
        }

        stage('Publish Allure Report (HTML)') {
            steps {
                // Публикация через HTML Publisher плагин
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: "${ALLURE_REPORT_DIR}",
                    reportFiles: 'index.html',
                    reportName: 'Allure Report'
                ])
            }
        }
    }

    post {
        always {
            junit 'Jefit_test/TestResults/*.trx'
            cleanWs()
        }
    }
}
