pipeline {
    agent any

    tools {
        allure 'Allure_2.35.1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                bat 'dotnet restore "Jefit_test/Jefit_test.sln"'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build "Jefit_test/Jefit_test.sln" --no-restore'
            }
        }

        stage('Test') {
            steps {
                bat 'dotnet test "Jefit_test/Jefit_test.sln" --no-build'
            }
        }
    }

    post {
        always {
            echo '✅ Test run is finished'

            // ✅ Добавляем Allure Environment
            bat '''
                echo OS=Windows > allure-results/environment.properties
                echo .NET=9.0 >> allure-results/environment.properties
            '''

            // ✅ Публикуем Allure отчет
            allure includeProperties: false, results: [[path: 'Jefit_test/bin/Debug/net9.0/allure-results']]
        }

        failure {
            echo '❌ Test run failed!'
        }
    }
}
